### PR TITLE
Add a Semigroup instance

### PR DESCRIPTION
**Pull request by k-bx**

### CODE REVIEW

**Comment by nikita-volkov** [comment]
Please check the compatibility with the older versions as per the Travis results. (Needs an explicit import of Data.Semigroup).

**Comment by k-bx** [comment]
@nikita-volkov looks good, removing a WIP

**Comment by k-bx** [comment]
I think this is ready to be merged. Thanks.

**Comment by nikita-volkov** [comment]
Thanks! It's released

**Pull request merged**
